services:
  web:
    restart: always
    build:
      context: ./web
      dockerfile: ./.nixpacks/Dockerfile
      args:
        CI: "true"
        NIXPACKS_METADATA: "node"
        NODE_ENV: "production"
        NPM_CONFIG_PRODUCTION: "false"
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
    networks:
      critino_net:
        ipv4_address: 172.16.238.12
  api:
    restart: always
    build:
      context: ./services/api
      dockerfile: ./.nixpacks/Dockerfile
      args:
        NIXPACKS_METADATA: python,poetry
        NIXPACKS_POETRY_VERSION: 1.3.1
        PIP_DEFAULT_TIMEOUT: 100
        PIP_DISABLE_PIP_VERSION_CHECK: 1
        PIP_NO_CACHE_DIR: 1
        PYTHONDONTWRITEBYTECODE: 1
        PYTHONFAULTHANDLER: 1
        PYTHONHASHSEED: random
        PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/app
    networks:
      critino_net:
        ipv4_address: 172.16.238.11

networks:
  critino_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
